# Generated by Django 4.2.3 on 2023-07-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0001_initial'),
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
    ]
